---

####################
# Generate SSH key pair
####################

#- name: Generates ssh key pair
#    shell: ssh-keygen -t rsa -N "" -q -f {{ new_priv_key }}
#    when: inventory_hostname == play_hosts[0]
#    delegate_to: localhost
#
#- name: Move new key into default location
#    shell: mv {{ new_priv_key }} ~/.ssh/id_rsa
#    when: inventory_hostname == play_hosts[0]
#    delegate_to: localhost

- name: Generate SSH keys
  shell: ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N ""
  args:
    creates: /root/.ssh/id_rsa