---

####################
# Generate SSH key pair
####################

- openssl_privatekey:
    path: /etc/ansuble/kops-privkey.pem
    size: 2048

- openssl_publickey:
    path: /etc/ansuble/kops-pubkey.pem
    privatekey_path: /etc/ansuble/kops-privkey.pem