---
###########################
# Setup Kubernetes Add-Ons
###########################

- hosts: localhost
  connection: local
  roles:
    - kubectl-config
    - storage
    - dashboard
    - heapster
    - external-dns
    #- route53-mapper
