---
###########################
# Setup Kubernetes Cluster
###########################

- hosts: localhost
  connection: local
  roles:
    - clone-git-repos
    - generate-ssh-keys
#    - create-vpc
#    - create-cluster
#    - install-istio
#    - deploy-istio
#    - deploy-aut
