---
###########################
# Setup Kubernetes Cluster
###########################

- hosts: localhost
  connection: local
  roles:
#    - lambda-delete
#    - lambda-install
    - create-vpc
    - create-cluster
