---
###########################
# Setup Kubernetes Cluster
###########################

- hosts: localhost
  connection: local
  roles:
#    - clone-git-repos
    - create-vpc
    - generate-ssh-keys
    - create-cluster
    - install-istio
    - deploy-istio
#    - deploy-aut
