---
###########################
# Setup Kubernetes Cluster
###########################

- hosts: localhost
  connection: local
  roles:
    - clone-git-repos
    - create-vpc
    - create-cluster
    - install-istio
    - deploy-istio
