---

############################################
# Delete the Kubernetes cluster
############################################

- hosts: localhost
  connection: local
  roles:
    - restore-kubectl-conf
    - delete-aut
    - delete-istio
    - delete-cluster
    - delete-vpc
