---

############################################
# Delete the Kubernetes cluster
############################################

- hosts: localhost
  connection: local
  roles:
    - lambda-delete
    - delete-cluster
