---
cluster_name: k8s.risk.dbg-devops.com
state_store: s3://k8s-risk-kops

# Remote access
ssh_public_key: ~/.ssh/id_rsa.pub

# Regions / Availability zones
aws_region: eu-central-1
aws_zones: eu-central-1a,eu-central-1b,eu-central-1c
# Use master_zones if you want your masters in different zones than worker nodes.
# Useful especially when you want 1 master in single zone but workers in several zones.
# When not defined, aws_zones will be sued instead
master_zones: eu-central-1a

# Network
dns_zone: dbg-devops.com
network_cidr: 172.35.0.0/16
kubernetes_networking: calico

# EC2 host sizing
master_size: m4.large
master_count: 1
master_volume_size: 100
node_size: m4.xlarge
node_count: 3
node_volume_size: 100
node_autoscaler_min: 3
node_autoscaler_max: 6

# Tags
tag_creator: en341
tag_owner: en341
tag_application: DAVe
tag_costcenter: 665050
tag_product: Risk
tag_confidentiality: None
tag_environment: DEV
