---
cluster_name: cluster1.customerk8s.com
state_store: s3://customerk8s

# Remote access
ssh_public_key: ~/.ssh/id_rsa.pub

# Regions / Availability zones
aws_region: us-east-1
aws_zones: us-east-1a,us-east-1b,us-east-1c
# Use master_zones if you want your masters in different zones than worker nodes.
# Useful especially when you want 1 master in single zone but workers in several zones.
# When not defined, aws_zones will be sued instead
master_zones: us-east-1a

# Network
vpc_name: customerk8s
dns_zone: customerk8s.com
network_cidr: 172.85.0.0/16
kubernetes_networking: calico

# EC2 host sizing
master_size: m3.medium
master_count: 1
master_volume_size: 100
node_size: m3.medium
node_count: 2
node_volume_size: 100
node_autoscaler_min: 3
node_autoscaler_max: 6

# Tags
tag_creator: None
tag_owner: None
tag_application: customer_cluster
tag_costcenter: None
tag_product: None
tag_confidentiality: None
tag_environment: customerk8s_a
