---

####################
# Deploy Istio
####################

- name: Deploy istio services
  shell: "{{ item }}"
  with_items:
  - kubectl apply -f /tufin-infra/istio-0.1.6/install/kubernetes/istio-rbac-beta.yaml
  - kubectl apply -f /tufin-infra/istio-0.1.6/install/kubernetes/istio.yaml