---

####################
# Deploy Aut
####################

- name: Deploy Kite
  shell: '{{ item }}'
  with_items:
  - 'kubectl create -f /tufin-infra/aut/deployment/kite/kite.yaml'


- name: Deploy aut db
  shell: '{{ item }}'
  with_items:
  - 'kubectl create -f <(istioctl kube-inject -f aut/deployment/db/aut_redis.yaml)'
  - 'kubectl create -f <(istioctl kube-inject -f aut/deployment/db/aut_redis_svc.yaml)'


- name: Deploy aut customer
  shell: '{{ item }}'
  with_items:
  - 'kubectl create -f <(istioctl kube-inject -f /tufin-infra/aut/deployment/customer/aut_customer_svc.yaml)'
  - 'kubectl create -f <(istioctl kube-inject -f /tufin-infra/aut/deployment/customer/aut_customer.yaml)'


- name: Deploy aut indexer
  shell: '{{ item }}'
  with_items:
  - 'kubectl create -f <(istioctl kube-inject -f /tufin-infra/aut/deployment/indexer/aut_indexer_svc.yaml)'
  - 'kubectl create -f <(istioctl kube-inject -f /tufin-infra/aut/deployment/indexer/aut_indexer.yaml)'

- name: Deploy aut posgres
  shell: '{{ item }}'
  with_items:
  - 'kubectl create -f <(istioctl kube-inject -f /tufin-infra/aut/deployment/postgres/aut_postgres_svc.yaml)'
  - 'kubectl create -f <(istioctl kube-inject -f /tufin-infra/aut/deployment/postgres/aut_postgres.yaml)'


- name: Deploy aut admin
  shell: '{{ item }}'
  with_items:
  - 'kubectl create -f <(istioctl kube-inject -f /tufin-infra/aut/deployment/admin/aut_admin_svc.yaml)'
  - 'kubectl create -f <(istioctl kube-inject -f /tufin-infra/aut/deployment/admin/aut_admin.yaml)'
