---

####################
# Create entities
####################

- name: Create S3 bucket
  s3_bucket:
    name: "{{ state_store | replace('s3://', '') }}"
    state: present
    region: "{{ aws_region }}"
    versioning: no
    tags:
      Name: "{{ state_store | replace('s3://', '') }}"
      Creator: "{{ tag_creator }}"
      Owner: "{{ tag_owner }}"
      Application: "{{ tag_application }}"
      CostCenter: "{{ tag_costcenter }}"
      Confidentiality: "{{ tag_confidentiality }}"
      Environment: "{{ tag_environment }}"


- name: Create VPC
  ec2_vpc_net:
    name: "{{ aws_region }}"
    state: present
    cidr_block: "{{ network_cidr }}"
    resource_tags: { "Environment":"{{ tag_environment }}" }
    region: "{{ aws_region }}"
  register: vpc_result


- name: Create internet gateway
  ec2_vpc_igw:
    vpc_id: "{{ vpc_result.vpc.id }}"
    state: present


- name: Create route53 private zone
  route53_zone:
    zone: "{{ dns_zone }}"
    state: present
    vpc_id: "{{ vpc_result.vpc.id }}"
    comment: for customer k8s cluster